### ISSUE TITLE
Ideias para novos respawns 

### ISSUE THREAD

**Issue by Dugordinho** [Yokaito/FuriaOT#4]
### Ideias para novos respawns 

**Feyrist LVL 60+** ( _Superfície_ ) 
**Monstros:** Pixie, Nymph, Swan Maiden, Faun, Dark Faun, Pooka, Twisted Pooka, Boogy

**Feyrist LVL 100+** ( _Nightmare Creatures Cave_ )
**Monstros:** Enfeebled Silencer, Weakened Frazzlemaw e **Kroazur** ( BOSS )

**Carnivora's Rocks LVL 250+** ( _Port Hope - Todos os monstros refletem dano físico_)
**Monstros:** Spiky Carnivor, Lumbering Carnivor, Menacing Carnivor

**Buried Cathedral LVL 250+** ( _Outlaw Camp - Venore_ )
**Monstros:** Arachnophobica, Burster Spectre, Gazer Spectre, Ripper Spectre e **Faceless Bane** (  BOSS )

**The Haunted Houses LVL 250+** ( _Temple - Venore_ )
**Monstros**: Arachnophobica, Gazer Spectre, Thanatursus

**Summer Court of the Dreamborn LVL 300+** ( _Entrada por Feyrist_ )
**Monstros**: Arachnophobica, Crazed Summer Rearguard, Crazed Summer Vanguard, Insane Siren, Lacewing Moth, Thanatursus

**Winter Court of the Dreamborn LVL 300+** 
**Monstros**: Arachnophobica, Crazed Winter Rearguard, Crazed Winter Vanguard, Hibernal Moth, Soul-Broken Harbinger, Thanatursus

**Warzone 4 LVL 200+**
**Monstros**: Chasm Spawn, Drillworm, Elder Wyrm, Lava Lurker, Mole e **The Baron from Below** ( BOSS )

**Warzone 5 LVL 200**
**Monstros**: Cave Devoure, High Voltage Elemental, Tunnel Tyrant e **The Count Of The Core** ( BOSS )

**Warzone 6 LVL 200**
**Monstros**: Deepworm, Diremaw, Humongous Fungus, Mole e **The Duke Of The Depths** ( BOSS )

**Comment by Yokaito** [comment]
> **OK** - Já puxei do global, falta apenas implementar.
Carnivora's Rocks LVL 250+ ( Port Hope - Todos os monstros refletem dano físico)
Monstros: Spiky Carnivor, Lumbering Carnivor, Menacing Carnivor

> **OK** - Já puxei do global, falta apenas implementar.
Buried Cathedral LVL 250+ ( Outlaw Camp - Venore )
Monstros: Arachnophobica, Burster Spectre, Gazer Spectre, Ripper Spectre e Faceless Bane ( BOSS )
