### ISSUE TITLE
Donate Paladin Helmet 

### ISSUE THREAD

**Issue by Boltada324** [Yokaito/FuriaOT#7]
Este helmet esta bugado, pois não abrange nenhum atributo ao personagem. Consigo imbuir, mas não ganho o atributo do imbue de Powerfull Void "Mana Leech"

Desde já, Agradeço pela atenção...
ATT; Boltada No Toba

**Comment by HttpsBR** [comment]
Ok, eu corrigindo o bug eu aviso aqui e fecho o tópico. 

Obrigado pelo issue, Att: ADM

**Comment by HttpsBR** [comment]
O issue foi analisado e realmente estamos com o problema no "Donate Paladin Helmet", a correção já foi aplicada e testado in game, OK!

Bug Corrigido, Att: ADM.

**Comment by HttpsBR** [comment]
> Este helmet esta bugado, pois não abrange nenhum atributo ao personagem. Consigo imbuir, mas não ganho o atributo do imbue de Powerfull Void "Mana Leech"
> 
> Desde já, Agradeço pela atenção...
> ATT; Boltada No Toba

O issue foi analisado e realmente estamos com o problema no "Donate Paladin Helmet", a correção já foi aplicada e testado in game, OK!

Bug Corrigido, Att: ADM.
