### ISSUE TITLE
Oramond

### ISSUE THREAD

**Issue by Benvenuttipedro** [Yokaito/FuriaOT#8]
boa tarde!

poderia adicionar a cidade de oramond no servidor, ela contem muitas hunts para high lvl 

Ly Xumbei

**Comment by Yokaito** [comment]
Em breve, atualizarei aqui , ja estou puxando algumas outras hunts. Vou deixar anotado

**Comment by Yokaito** [comment]
Hunts puxadas, estou terminando de fazer a nova sala de hunts onde elas estarão incluídas.
